### ISSUE TITLE
create specific api requests for each code system (ORPHA, MONDO, etc)

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/rarelink#52]

**Comment by aslgraefe** [comment]
@frehburg  this will be part of phenopacket_mapper, right?

**Comment by aslgraefe** [comment]
closing this, will be integrated via OAK https://github.com/INCATools/ontology-access-kit  within the RareLinkCDM-LinkML schema, so that REDCap data is automatically enriched with the displays from terminology servers
