### ISSUE TITLE
Allow repeating rows for repeating elements in redcap

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/rarelink#64]

**Comment by aslgraefe** [comment]
![image](https://github.com/user-attachments/assets/1a82de74-6cc7-42a9-a3b3-c2e29dc2804c)

**Comment by aslgraefe** [comment]
@frehburg

**Comment by aslgraefe** [comment]
closing this @frehburg 
repitions are now defined in the RareLinkCDM-LinkML.yaml schemas and geenerated/validated within the hierarchical .json structures.
